// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Run `flutterfire configure` to regenerate this file with your
/// actual Firebase project values.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── PLACEHOLDER VALUES ──────────────────────────────────────────────────
  // Run `flutterfire configure` to replace these with your real project values.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtJGIFsyRNxA_Frm3vmPohIVdghezITQg',
    appId: '1:947560045117:android:56ca86a4f8d01636e22854',
    messagingSenderId: '947560045117',
    projectId: 'lalafo-clone',
    storageBucket: 'lalafo-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzxeY6bm3zLMmDycG9t783oukFbPcuEwA',
    appId: '1:947560045117:ios:90518ead3bc5e6fde22854',
    messagingSenderId: '947560045117',
    projectId: 'lalafo-clone',
    storageBucket: 'lalafo-clone.firebasestorage.app',
    iosBundleId: 'com.lalafo.lalafoClone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA25XB6syDD9_-5159eS1ByzHUM51tSCWw',
    appId: '1:947560045117:web:a190646fd1aac991e22854',
    messagingSenderId: '947560045117',
    projectId: 'lalafo-clone',
    authDomain: 'lalafo-clone.firebaseapp.com',
    storageBucket: 'lalafo-clone.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzxeY6bm3zLMmDycG9t783oukFbPcuEwA',
    appId: '1:947560045117:ios:90518ead3bc5e6fde22854',
    messagingSenderId: '947560045117',
    projectId: 'lalafo-clone',
    storageBucket: 'lalafo-clone.firebasestorage.app',
    iosBundleId: 'com.lalafo.lalafoClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA25XB6syDD9_-5159eS1ByzHUM51tSCWw',
    appId: '1:947560045117:web:a190646fd1aac991e22854',
    messagingSenderId: '947560045117',
    projectId: 'lalafo-clone',
    authDomain: 'lalafo-clone.firebaseapp.com',
    storageBucket: 'lalafo-clone.firebasestorage.app',
  );
}